//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.searchws.search.wsdl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "JaxwsSearch", targetNamespace = "http://searchws.sirius.com/search/wsdl", wsdlLocation = "WEB-INF/wsdl/JaxwsSearch.wsdl")
public class JaxwsSearch
    extends Service
{

    private final static URL JAXWSSEARCH_WSDL_LOCATION;
    private final static WebServiceException JAXWSSEARCH_EXCEPTION;
    private final static QName JAXWSSEARCH_QNAME = new QName("http://searchws.sirius.com/search/wsdl", "JaxwsSearch");

    static {
            JAXWSSEARCH_WSDL_LOCATION = com.sirius.searchws.search.wsdl.JaxwsSearch.class.getResource("/WEB-INF/wsdl/JaxwsSearch.wsdl");
        WebServiceException e = null;
        if (JAXWSSEARCH_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/JaxwsSearch.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        JAXWSSEARCH_EXCEPTION = e;
    }

    public JaxwsSearch() {
        super(__getWsdlLocation(), JAXWSSEARCH_QNAME);
    }

    public JaxwsSearch(WebServiceFeature... features) {
        super(__getWsdlLocation(), JAXWSSEARCH_QNAME, features);
    }

    public JaxwsSearch(URL wsdlLocation) {
        super(wsdlLocation, JAXWSSEARCH_QNAME);
    }

    public JaxwsSearch(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JAXWSSEARCH_QNAME, features);
    }

    public JaxwsSearch(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JaxwsSearch(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Search
     */
    @WebEndpoint(name = "search")
    public Search getSearch() {
        return super.getPort(new QName("http://searchws.sirius.com/search/wsdl", "search"), Search.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Search
     */
    @WebEndpoint(name = "search")
    public Search getSearch(WebServiceFeature... features) {
        return super.getPort(new QName("http://searchws.sirius.com/search/wsdl", "search"), Search.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JAXWSSEARCH_EXCEPTION!= null) {
            throw JAXWSSEARCH_EXCEPTION;
        }
        return JAXWSSEARCH_WSDL_LOCATION;
    }

}
