//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.searchws.search.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sirius.searchws.search.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BudgetSearchResponse_QNAME = new QName("http://searchws.sirius.com/search/wsdl", "budgetSearchResponse");
    private final static QName _BudgetSearch_QNAME = new QName("http://searchws.sirius.com/search/wsdl", "budgetSearch");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sirius.searchws.search.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BudgetSearch }
     * 
     */
    public BudgetSearch createBudgetSearch() {
        return new BudgetSearch();
    }

    /**
     * Create an instance of {@link BudgetSearchResponse }
     * 
     */
    public BudgetSearchResponse createBudgetSearchResponse() {
        return new BudgetSearchResponse();
    }

    /**
     * Create an instance of {@link ActualvBudgetBean }
     * 
     */
    public ActualvBudgetBean createActualvBudgetBean() {
        return new ActualvBudgetBean();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BudgetSearchResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://searchws.sirius.com/search/wsdl", name = "budgetSearchResponse")
    public JAXBElement<BudgetSearchResponse> createBudgetSearchResponse(BudgetSearchResponse value) {
        return new JAXBElement<BudgetSearchResponse>(_BudgetSearchResponse_QNAME, BudgetSearchResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BudgetSearch }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://searchws.sirius.com/search/wsdl", name = "budgetSearch")
    public JAXBElement<BudgetSearch> createBudgetSearch(BudgetSearch value) {
        return new JAXBElement<BudgetSearch>(_BudgetSearch_QNAME, BudgetSearch.class, null, value);
    }

}
