//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.searchws.search.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

@WebService(name = "Search", targetNamespace = "http://searchws.sirius.com/search/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Search {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.sirius.searchws.search.wsdl.BudgetSearchResponse
     */
    @WebMethod(action = "budgetSearch")
    @WebResult(name = "budgetSearchResponse", targetNamespace = "http://searchws.sirius.com/search/wsdl", partName = "parameters")
    @Action(input = "budgetSearch", output = "http://searchws.sirius.com/search/wsdl/Search/searchResponse")
    public BudgetSearchResponse search(
        @WebParam(name = "budgetSearch", targetNamespace = "http://searchws.sirius.com/search/wsdl", partName = "parameters")
        BudgetSearch parameters);

}
