//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.searchws.search.wsdl;

<<<<<<< HEAD
=======
import java.util.List;
>>>>>>> 18e547fb64dffb80d3e1cfbf01974df0bd035dfc
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
<<<<<<< HEAD
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

@WebService(name = "Search", targetNamespace = "http://searchws.sirius.com/search/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
=======
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "Search", targetNamespace = "http://searchws.sirius.com/search/wsdl")
>>>>>>> 18e547fb64dffb80d3e1cfbf01974df0bd035dfc
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Search {


    /**
     * 
<<<<<<< HEAD
     * @param parameters
     * @return
     *     returns com.sirius.searchws.search.wsdl.BudgetSearchResponse
     */
    @WebMethod(action = "budgetSearch")
    @WebResult(name = "budgetSearchResponse", targetNamespace = "http://searchws.sirius.com/search/wsdl", partName = "parameters")
    @Action(input = "budgetSearch", output = "http://searchws.sirius.com/search/wsdl/Search/searchResponse")
    public BudgetSearchResponse search(
        @WebParam(name = "budgetSearch", targetNamespace = "http://searchws.sirius.com/search/wsdl", partName = "parameters")
        BudgetSearch parameters);
=======
     * @param report
     * @param location
     * @param from
     * @param to
     * @return
     *     returns java.util.List<com.sirius.searchws.search.wsdl.ActualvBudgetBean>
     */
    @WebMethod(action = "budgetSearch")
    @WebResult(name = "budgetSearchReturn", targetNamespace = "http://searchws.sirius.com/search/wsdl")
    @RequestWrapper(localName = "budgetSearch", targetNamespace = "http://searchws.sirius.com/search/wsdl", className = "com.sirius.searchws.search.wsdl.BudgetSearch")
    @ResponseWrapper(localName = "budgetSearchResponse", targetNamespace = "http://searchws.sirius.com/search/wsdl", className = "com.sirius.searchws.search.wsdl.BudgetSearchResponse")
    @Action(input = "budgetSearch", output = "http://searchws.sirius.com/search/wsdl/Search/budgetSearchResponse")
    public List<ActualvBudgetBean> budgetSearch(
        @WebParam(name = "location", targetNamespace = "http://searchws.sirius.com/search/wsdl")
        int location,
        @WebParam(name = "from", targetNamespace = "http://searchws.sirius.com/search/wsdl")
        XMLGregorianCalendar from,
        @WebParam(name = "to", targetNamespace = "http://searchws.sirius.com/search/wsdl")
        XMLGregorianCalendar to,
        @WebParam(name = "report", targetNamespace = "http://searchws.sirius.com/search/wsdl")
        String report);
>>>>>>> 18e547fb64dffb80d3e1cfbf01974df0bd035dfc

}
