//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.loginws.login.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getEmployeeByCredentialsResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getEmployeeByCredentialsResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="getEmployeeByCredentialsReturn" type="{http://www.w3.org/2001/XMLSchema}int" form="qualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getEmployeeByCredentialsResponse", propOrder = {
    "getEmployeeByCredentialsReturn"
})
public class GetEmployeeByCredentialsResponse {

    protected int getEmployeeByCredentialsReturn;

    /**
     * Gets the value of the getEmployeeByCredentialsReturn property.
     * 
     */
    public int getGetEmployeeByCredentialsReturn() {
        return getEmployeeByCredentialsReturn;
    }

    /**
     * Sets the value of the getEmployeeByCredentialsReturn property.
     * 
     */
    public void setGetEmployeeByCredentialsReturn(int value) {
        this.getEmployeeByCredentialsReturn = value;
    }

}
