//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.loginws.login.wsdl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "JaxwsLogin", targetNamespace = "http://loginws.sirius.com/login/wsdl", wsdlLocation = "WEB-INF/wsdl/JaxwsLogin.wsdl")
public class JaxwsLogin
    extends Service
{

    private final static URL JAXWSLOGIN_WSDL_LOCATION;
    private final static WebServiceException JAXWSLOGIN_EXCEPTION;
    private final static QName JAXWSLOGIN_QNAME = new QName("http://loginws.sirius.com/login/wsdl", "JaxwsLogin");

    static {
            JAXWSLOGIN_WSDL_LOCATION = com.sirius.loginws.login.wsdl.JaxwsLogin.class.getResource("/WEB-INF/wsdl/JaxwsLogin.wsdl");
        WebServiceException e = null;
        if (JAXWSLOGIN_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/JaxwsLogin.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        JAXWSLOGIN_EXCEPTION = e;
    }

    public JaxwsLogin() {
        super(__getWsdlLocation(), JAXWSLOGIN_QNAME);
    }

    public JaxwsLogin(WebServiceFeature... features) {
        super(__getWsdlLocation(), JAXWSLOGIN_QNAME, features);
    }

    public JaxwsLogin(URL wsdlLocation) {
        super(wsdlLocation, JAXWSLOGIN_QNAME);
    }

    public JaxwsLogin(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JAXWSLOGIN_QNAME, features);
    }

    public JaxwsLogin(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JaxwsLogin(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Login
     */
    @WebEndpoint(name = "login")
    public Login getLogin() {
        return super.getPort(new QName("http://loginws.sirius.com/login/wsdl", "login"), Login.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Login
     */
    @WebEndpoint(name = "login")
    public Login getLogin(WebServiceFeature... features) {
        return super.getPort(new QName("http://loginws.sirius.com/login/wsdl", "login"), Login.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JAXWSLOGIN_EXCEPTION!= null) {
            throw JAXWSLOGIN_EXCEPTION;
        }
        return JAXWSLOGIN_WSDL_LOCATION;
    }

}
