//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.loginws.login.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "Login", targetNamespace = "http://loginws.sirius.com/login/wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Login {


    /**
     * 
     * @param password
     * @param email
     * @return
     *     returns int
     */
    @WebMethod(action = "getEmployeeByCredentials")
    @WebResult(name = "getEmployeeByCredentialsReturn", targetNamespace = "http://loginws.sirius.com/login/wsdl")
    @RequestWrapper(localName = "getEmployeeByCredentials", targetNamespace = "http://loginws.sirius.com/login/wsdl", className = "com.sirius.loginws.login.wsdl.GetEmployeeByCredentials")
    @ResponseWrapper(localName = "getEmployeeByCredentialsResponse", targetNamespace = "http://loginws.sirius.com/login/wsdl", className = "com.sirius.loginws.login.wsdl.GetEmployeeByCredentialsResponse")
    public int getEmployeeByCredentials(
        @WebParam(name = "email", targetNamespace = "http://loginws.sirius.com/login/wsdl")
        String email,
        @WebParam(name = "password", targetNamespace = "http://loginws.sirius.com/login/wsdl")
        String password);

}
