//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.loginws.login.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sirius.loginws.login.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetEmployeeByCredentials_QNAME = new QName("http://loginws.sirius.com/login/wsdl", "getEmployeeByCredentials");
    private final static QName _GetEmployeeByCredentialsResponse_QNAME = new QName("http://loginws.sirius.com/login/wsdl", "getEmployeeByCredentialsResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sirius.loginws.login.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetEmployeeByCredentials }
     * 
     */
    public GetEmployeeByCredentials createGetEmployeeByCredentials() {
        return new GetEmployeeByCredentials();
    }

    /**
     * Create an instance of {@link GetEmployeeByCredentialsResponse }
     * 
     */
    public GetEmployeeByCredentialsResponse createGetEmployeeByCredentialsResponse() {
        return new GetEmployeeByCredentialsResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmployeeByCredentials }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loginws.sirius.com/login/wsdl", name = "getEmployeeByCredentials")
    public JAXBElement<GetEmployeeByCredentials> createGetEmployeeByCredentials(GetEmployeeByCredentials value) {
        return new JAXBElement<GetEmployeeByCredentials>(_GetEmployeeByCredentials_QNAME, GetEmployeeByCredentials.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmployeeByCredentialsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://loginws.sirius.com/login/wsdl", name = "getEmployeeByCredentialsResponse")
    public JAXBElement<GetEmployeeByCredentialsResponse> createGetEmployeeByCredentialsResponse(GetEmployeeByCredentialsResponse value) {
        return new JAXBElement<GetEmployeeByCredentialsResponse>(_GetEmployeeByCredentialsResponse_QNAME, GetEmployeeByCredentialsResponse.class, null, value);
    }

}
