//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.product.service.main.product.wsdl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "Product", targetNamespace = "http://main.service.product.sirius.com/product/wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Product {


    /**
     * 
     * @param id
     * @return
     *     returns com.sirius.product.service.main.product.wsdl.ProductBean
     */
    @WebMethod(action = "getProductByID")
    @WebResult(name = "getProductByIDReturn", targetNamespace = "http://main.service.product.sirius.com/product/wsdl")
    @RequestWrapper(localName = "getProductByID", targetNamespace = "http://main.service.product.sirius.com/product/wsdl", className = "com.sirius.product.service.main.product.wsdl.GetProductByID")
    @ResponseWrapper(localName = "getProductByIDResponse", targetNamespace = "http://main.service.product.sirius.com/product/wsdl", className = "com.sirius.product.service.main.product.wsdl.GetProductByIDResponse")
    @Action(input = "getProductByID", output = "http://main.service.product.sirius.com/product/wsdl/Product/getProductByIDResponse")
    public ProductBean getProductByID(
        @WebParam(name = "ID", targetNamespace = "http://main.service.product.sirius.com/product/wsdl")
        int id);

    /**
     * 
     * @param type
     * @return
     *     returns java.util.List<com.sirius.product.service.main.product.wsdl.ProductBean>
     */
    @WebMethod(action = "getAllProductsByType")
    @WebResult(name = "getAllProductsByTypeReturn", targetNamespace = "http://main.service.product.sirius.com/product/wsdl")
    @RequestWrapper(localName = "getAllProductsByType", targetNamespace = "http://main.service.product.sirius.com/product/wsdl", className = "com.sirius.product.service.main.product.wsdl.GetAllProductsByType")
    @ResponseWrapper(localName = "getAllProductByTypeResponse", targetNamespace = "http://main.service.product.sirius.com/product/wsdl", className = "com.sirius.product.service.main.product.wsdl.GetAllProductByTypeResponse")
    @Action(input = "getAllProductsByType", output = "http://main.service.product.sirius.com/product/wsdl/Product/getAllProductsByTypeResponse")
    public List<ProductBean> getAllProductsByType(
        @WebParam(name = "type", targetNamespace = "http://main.service.product.sirius.com/product/wsdl")
        String type);

}
