//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.adminws.officeadmin.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getOfficeAdminResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getOfficeAdminResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="getOfficeAdminReturn" type="{http://adminws.sirius.com/officeAdmin/wsdl}employeeBean" minOccurs="0" form="qualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getOfficeAdminResponse", propOrder = {
    "getOfficeAdminReturn"
})
public class GetOfficeAdminResponse {

    protected EmployeeBean getOfficeAdminReturn;

    /**
     * Gets the value of the getOfficeAdminReturn property.
     * 
     * @return
     *     possible object is
     *     {@link EmployeeBean }
     *     
     */
    public EmployeeBean getGetOfficeAdminReturn() {
        return getOfficeAdminReturn;
    }

    /**
     * Sets the value of the getOfficeAdminReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployeeBean }
     *     
     */
    public void setGetOfficeAdminReturn(EmployeeBean value) {
        this.getOfficeAdminReturn = value;
    }

}
