//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.service.superadmin.superadmin.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getEmployeeIdByNameResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getEmployeeIdByNameResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="getEmployeeIdByNameReturn" type="{http://www.w3.org/2001/XMLSchema}int" form="qualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getEmployeeIdByNameResponse", propOrder = {
    "getEmployeeIdByNameReturn"
})
public class GetEmployeeIdByNameResponse {

    protected int getEmployeeIdByNameReturn;

    /**
     * Gets the value of the getEmployeeIdByNameReturn property.
     * 
     */
    public int getGetEmployeeIdByNameReturn() {
        return getEmployeeIdByNameReturn;
    }

    /**
     * Sets the value of the getEmployeeIdByNameReturn property.
     * 
     */
    public void setGetEmployeeIdByNameReturn(int value) {
        this.getEmployeeIdByNameReturn = value;
    }

}
