//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.service.superadmin.superadmin.wsdl;

import java.math.BigDecimal;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "SuperAdmin", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SuperAdmin {


    /**
     * 
     * @param locationId
     * @param budget
     * @return
     *     returns boolean
     */
    @WebMethod(action = "setBudgetByLocation")
    @WebResult(name = "setBudgetByLocationReturn", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl")
    @RequestWrapper(localName = "setBudgetByLocation", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl", className = "com.sirius.service.superadmin.superadmin.wsdl.SetBudgetByLocation")
    @ResponseWrapper(localName = "setBudgetByLocationResponse", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl", className = "com.sirius.service.superadmin.superadmin.wsdl.SetBudgetByLocationResponse")
    @Action(input = "setBudgetByLocation", output = "http://superadmin.service.sirius.com/superadmin/wsdl/SuperAdmin/setBudgetByLocationResponse")
    public boolean setBudgetByLocation(
        @WebParam(name = "budget", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl")
        BigDecimal budget,
        @WebParam(name = "locationId", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl")
        int locationId);

    /**
     * 
     * @param locationId
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod(action = "getBudgetByLocation")
    @WebResult(name = "getBudgetByLocationReturn", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl")
    @RequestWrapper(localName = "getBudgetByLocation", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl", className = "com.sirius.service.superadmin.superadmin.wsdl.GetBudgetByLocation")
    @ResponseWrapper(localName = "getBudgetByLocationResponse", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl", className = "com.sirius.service.superadmin.superadmin.wsdl.GetBudgetByLocationResponse")
    @Action(input = "getBudgetByLocation", output = "http://superadmin.service.sirius.com/superadmin/wsdl/SuperAdmin/getBudgetByLocationResponse")
    public BigDecimal getBudgetByLocation(
        @WebParam(name = "locationId", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl")
        int locationId);

    /**
     * 
     * @param state
     * @param creatorId
     * @param city
     * @return
     *     returns boolean
     */
    @WebMethod(action = "addLocation")
    @WebResult(name = "addLocationReturn", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl")
    @RequestWrapper(localName = "addLocation", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl", className = "com.sirius.service.superadmin.superadmin.wsdl.AddLocation")
    @ResponseWrapper(localName = "addLocationResponse", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl", className = "com.sirius.service.superadmin.superadmin.wsdl.AddLocationResponse")
    @Action(input = "addLocation", output = "http://superadmin.service.sirius.com/superadmin/wsdl/SuperAdmin/addLocationResponse")
    public boolean addLocation(
        @WebParam(name = "city", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl")
        String city,
        @WebParam(name = "state", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl")
        String state,
        @WebParam(name = "creatorId", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl")
        int creatorId);

    /**
     * 
     * @param locationId
     * @param updaterId
     * @param adminId
     * @return
     *     returns boolean
     */
    @WebMethod(action = "assignAdmin")
    @WebResult(name = "assignAdminReturn", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl")
    @RequestWrapper(localName = "assignAdmin", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl", className = "com.sirius.service.superadmin.superadmin.wsdl.AssignAdmin")
    @ResponseWrapper(localName = "assignAdminResponse", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl", className = "com.sirius.service.superadmin.superadmin.wsdl.AssignAdminResponse")
    @Action(input = "assignAdmin", output = "http://superadmin.service.sirius.com/superadmin/wsdl/SuperAdmin/assignAdminResponse")
    public boolean assignAdmin(
        @WebParam(name = "locationId", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl")
        int locationId,
        @WebParam(name = "adminId", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl")
        int adminId,
        @WebParam(name = "updaterId", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl")
        int updaterId);

    /**
     * 
     * @return
     *     returns java.util.List<com.sirius.service.superadmin.superadmin.wsdl.OfficeBean>
     */
    @WebMethod(action = "getOffices")
    @WebResult(name = "getOfficesReturn", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl")
    @RequestWrapper(localName = "getOffices", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl", className = "com.sirius.service.superadmin.superadmin.wsdl.GetOffices")
    @ResponseWrapper(localName = "getOfficesResponse", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl", className = "com.sirius.service.superadmin.superadmin.wsdl.GetOfficesResponse")
    @Action(input = "getOffices", output = "http://superadmin.service.sirius.com/superadmin/wsdl/SuperAdmin/getOfficesResponse")
    public List<OfficeBean> getOffices();

    /**
     * 
     * @param name
     * @return
     *     returns int
     */
    @WebMethod(action = "getEmployeeIdByName")
    @WebResult(name = "getEmployeeIdByNameReturn", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl")
    @RequestWrapper(localName = "getEmployeeIdByName", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl", className = "com.sirius.service.superadmin.superadmin.wsdl.GetEmployeeIdByName")
    @ResponseWrapper(localName = "getEmployeeIdByNameResponse", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl", className = "com.sirius.service.superadmin.superadmin.wsdl.GetEmployeeIdByNameResponse")
    @Action(input = "getEmployeeIdByName", output = "http://superadmin.service.sirius.com/superadmin/wsdl/SuperAdmin/getEmployeeIdByNameResponse")
    public int getEmployeeIdByName(
        @WebParam(name = "name", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl")
        String name);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(action = "getOfficeAdminNames")
    @WebResult(name = "getOfficeAdminNamesReturn", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl")
    @RequestWrapper(localName = "getOfficeAdminNames", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl", className = "com.sirius.service.superadmin.superadmin.wsdl.GetOfficeAdminNames")
    @ResponseWrapper(localName = "getOfficeAdminNamesResponse", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl", className = "com.sirius.service.superadmin.superadmin.wsdl.GetOfficeAdminNamesResponse")
    @Action(input = "getOfficeAdminNames", output = "http://superadmin.service.sirius.com/superadmin/wsdl/SuperAdmin/getOfficeAdminNamesResponse")
    public List<String> getOfficeAdminNames();

}
