//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.service.superadmin.superadmin.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

@WebService(name = "SuperAdminService", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SuperAdminService {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.sirius.service.superadmin.superadmin.wsdl.SetBudgetByLocationResponse
     */
    @WebMethod(action = "SetBudgetByLocation")
    @WebResult(name = "SetBudgetByLocationResponse", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl", partName = "parameters")
    @Action(input = "SetBudgetByLocation", output = "http://superadmin.service.sirius.com/superadmin/wsdl/SuperAdminService/setBudgetByLocationResponse")
    public SetBudgetByLocationResponse setBudgetByLocation(
        @WebParam(name = "SetBudgetByLocation", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl", partName = "parameters")
        SetBudgetByLocation parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.sirius.service.superadmin.superadmin.wsdl.GetBudgetByLocationResponse
     */
    @WebMethod(action = "GetBudgetByLocation")
    @WebResult(name = "GetBudgetByLocationResponse", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl", partName = "parameters")
    @Action(input = "GetBudgetByLocation", output = "http://superadmin.service.sirius.com/superadmin/wsdl/SuperAdminService/getBudgetByLocationResponse")
    public GetBudgetByLocationResponse getBudgetByLocation(
        @WebParam(name = "GetBudgetByLocation", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl", partName = "parameters")
        GetBudgetByLocation parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.sirius.service.superadmin.superadmin.wsdl.AddLocationResponse
     */
    @WebMethod(action = "AddLocation")
    @WebResult(name = "AddLocationResponse", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl", partName = "parameters")
    @Action(input = "AddLocation", output = "http://superadmin.service.sirius.com/superadmin/wsdl/SuperAdminService/addLocationResponse")
    public AddLocationResponse addLocation(
        @WebParam(name = "AddLocation", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl", partName = "parameters")
        AddLocation parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.sirius.service.superadmin.superadmin.wsdl.AssignAdminResponse
     */
    @WebMethod(action = "AssignAdmin")
    @WebResult(name = "AssignAdminResponse", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl", partName = "parameters")
    @Action(input = "AssignAdmin", output = "http://superadmin.service.sirius.com/superadmin/wsdl/SuperAdminService/assignAdminResponse")
    public AssignAdminResponse assignAdmin(
        @WebParam(name = "AssignAdmin", targetNamespace = "http://superadmin.service.sirius.com/superadmin/wsdl", partName = "parameters")
        AssignAdmin parameters);

}
