//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.locationws.location.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getLocationStringByLocationIdResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getLocationStringByLocationIdResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="getLocationStringByLocationIdReturn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0" form="qualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getLocationStringByLocationIdResponse", propOrder = {
    "getLocationStringByLocationIdReturn"
})
public class GetLocationStringByLocationIdResponse {

    @XmlElement(namespace = "http://locationws.sirius.com/location/wsdl")
    protected String getLocationStringByLocationIdReturn;

    /**
     * Gets the value of the getLocationStringByLocationIdReturn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGetLocationStringByLocationIdReturn() {
        return getLocationStringByLocationIdReturn;
    }

    /**
     * Sets the value of the getLocationStringByLocationIdReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGetLocationStringByLocationIdReturn(String value) {
        this.getLocationStringByLocationIdReturn = value;
    }

}
