//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.loctionws.location.wsdl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "JaxwsLocation", targetNamespace = "http://locationws.sirius.com/location/wsdl", wsdlLocation = "WEB-INF/wsdl/JaxwsLocation.wsdl")
public class JaxwsLocation
    extends Service
{

    private final static URL JAXWSLOCATION_WSDL_LOCATION;
    private final static WebServiceException JAXWSLOCATION_EXCEPTION;
    private final static QName JAXWSLOCATION_QNAME = new QName("http://locationws.sirius.com/location/wsdl", "JaxwsLocation");

    static {
            JAXWSLOCATION_WSDL_LOCATION = com.sirius.loctionws.location.wsdl.JaxwsLocation.class.getResource("/WEB-INF/wsdl/JaxwsLocation.wsdl");
        WebServiceException e = null;
        if (JAXWSLOCATION_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/JaxwsLocation.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        JAXWSLOCATION_EXCEPTION = e;
    }

    public JaxwsLocation() {
        super(__getWsdlLocation(), JAXWSLOCATION_QNAME);
    }

    public JaxwsLocation(WebServiceFeature... features) {
        super(__getWsdlLocation(), JAXWSLOCATION_QNAME, features);
    }

    public JaxwsLocation(URL wsdlLocation) {
        super(wsdlLocation, JAXWSLOCATION_QNAME);
    }

    public JaxwsLocation(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JAXWSLOCATION_QNAME, features);
    }

    public JaxwsLocation(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JaxwsLocation(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Location
     */
    @WebEndpoint(name = "location")
    public Location getLocation() {
        return super.getPort(new QName("http://locationws.sirius.com/location/wsdl", "location"), Location.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Location
     */
    @WebEndpoint(name = "location")
    public Location getLocation(WebServiceFeature... features) {
        return super.getPort(new QName("http://locationws.sirius.com/location/wsdl", "location"), Location.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JAXWSLOCATION_EXCEPTION!= null) {
            throw JAXWSLOCATION_EXCEPTION;
        }
        return JAXWSLOCATION_WSDL_LOCATION;
    }

}
