//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.service.cart.cart.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getProductQuantityInCartByProductIdResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getProductQuantityInCartByProductIdResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="getProductQuantityInCartByProductIdReturn" type="{http://www.w3.org/2001/XMLSchema}int" form="qualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getProductQuantityInCartByProductIdResponse", propOrder = {
    "getProductQuantityInCartByProductIdReturn"
})
public class GetProductQuantityInCartByProductIdResponse {

    protected int getProductQuantityInCartByProductIdReturn;

    /**
     * Gets the value of the getProductQuantityInCartByProductIdReturn property.
     * 
     */
    public int getGetProductQuantityInCartByProductIdReturn() {
        return getProductQuantityInCartByProductIdReturn;
    }

    /**
     * Sets the value of the getProductQuantityInCartByProductIdReturn property.
     * 
     */
    public void setGetProductQuantityInCartByProductIdReturn(int value) {
        this.getProductQuantityInCartByProductIdReturn = value;
    }

}
