//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.service.cart.cart.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sirius.service.cart.cart.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UpdateProductQuantityInCartResponse_QNAME = new QName("http://cart.service.sirius.com/cart/wsdl", "updateProductQuantityInCartResponse");
    private final static QName _RemoveProductFromCartResponse_QNAME = new QName("http://cart.service.sirius.com/cart/wsdl", "removeProductFromCartResponse");
    private final static QName _UpdateProductQuantityInCart_QNAME = new QName("http://cart.service.sirius.com/cart/wsdl", "updateProductQuantityInCart");
    private final static QName _GetAllProductsInCartResponse_QNAME = new QName("http://cart.service.sirius.com/cart/wsdl", "getAllProductsInCartResponse");
    private final static QName _RemoveProductFromCart_QNAME = new QName("http://cart.service.sirius.com/cart/wsdl", "removeProductFromCart");
    private final static QName _GetAllProductsInCart_QNAME = new QName("http://cart.service.sirius.com/cart/wsdl", "getAllProductsInCart");
    private final static QName _SaveOrderResponse_QNAME = new QName("http://cart.service.sirius.com/cart/wsdl", "saveOrderResponse");
    private final static QName _SaveOrder_QNAME = new QName("http://cart.service.sirius.com/cart/wsdl", "saveOrder");
    private final static QName _GetAllProductsInCartByProductTypeResponse_QNAME = new QName("http://cart.service.sirius.com/cart/wsdl", "getAllProductsInCartByProductTypeResponse");
    private final static QName _GetAllProductsInCartByProductType_QNAME = new QName("http://cart.service.sirius.com/cart/wsdl", "getAllProductsInCartByProductType");
    private final static QName _GetMostRecentBudgetByLocation_QNAME = new QName("http://cart.service.sirius.com/cart/wsdl", "getMostRecentBudgetByLocation");
    private final static QName _GetAllOrdersByProductTypeResponse_QNAME = new QName("http://cart.service.sirius.com/cart/wsdl", "getAllOrdersByProductTypeResponse");
    private final static QName _GetAllOrdersByProductType_QNAME = new QName("http://cart.service.sirius.com/cart/wsdl", "getAllOrdersByProductType");
    private final static QName _GetAllSavedOrdersResponse_QNAME = new QName("http://cart.service.sirius.com/cart/wsdl", "getAllSavedOrdersResponse");
    private final static QName _GetAllSavedOrders_QNAME = new QName("http://cart.service.sirius.com/cart/wsdl", "getAllSavedOrders");
    private final static QName _GetMostRecentBudgetByLocationsResponse_QNAME = new QName("http://cart.service.sirius.com/cart/wsdl", "getMostRecentBudgetByLocationsResponse");
    private final static QName _GetProductQuantityInCartByProductIdResponse_QNAME = new QName("http://cart.service.sirius.com/cart/wsdl", "getProductQuantityInCartByProductIdResponse");
    private final static QName _GetOrderByOrderNameResponse_QNAME = new QName("http://cart.service.sirius.com/cart/wsdl", "getOrderByOrderNameResponse");
    private final static QName _GetProductQuantityInCartByProductId_QNAME = new QName("http://cart.service.sirius.com/cart/wsdl", "getProductQuantityInCartByProductId");
    private final static QName _AddProductToCartResponse_QNAME = new QName("http://cart.service.sirius.com/cart/wsdl", "addProductToCartResponse");
    private final static QName _GetOrderByOrderName_QNAME = new QName("http://cart.service.sirius.com/cart/wsdl", "getOrderByOrderName");
    private final static QName _AddProductToCart_QNAME = new QName("http://cart.service.sirius.com/cart/wsdl", "addProductToCart");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sirius.service.cart.cart.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllSavedOrders }
     * 
     */
    public GetAllSavedOrders createGetAllSavedOrders() {
        return new GetAllSavedOrders();
    }

    /**
     * Create an instance of {@link GetAllOrdersByProductType }
     * 
     */
    public GetAllOrdersByProductType createGetAllOrdersByProductType() {
        return new GetAllOrdersByProductType();
    }

    /**
     * Create an instance of {@link GetAllSavedOrdersResponse }
     * 
     */
    public GetAllSavedOrdersResponse createGetAllSavedOrdersResponse() {
        return new GetAllSavedOrdersResponse();
    }

    /**
     * Create an instance of {@link GetAllOrdersByProductTypeResponse }
     * 
     */
    public GetAllOrdersByProductTypeResponse createGetAllOrdersByProductTypeResponse() {
        return new GetAllOrdersByProductTypeResponse();
    }

    /**
     * Create an instance of {@link GetMostRecentBudgetByLocation }
     * 
     */
    public GetMostRecentBudgetByLocation createGetMostRecentBudgetByLocation() {
        return new GetMostRecentBudgetByLocation();
    }

    /**
     * Create an instance of {@link AddProductToCart }
     * 
     */
    public AddProductToCart createAddProductToCart() {
        return new AddProductToCart();
    }

    /**
     * Create an instance of {@link GetProductQuantityInCartByProductId }
     * 
     */
    public GetProductQuantityInCartByProductId createGetProductQuantityInCartByProductId() {
        return new GetProductQuantityInCartByProductId();
    }

    /**
     * Create an instance of {@link AddProductToCartResponse }
     * 
     */
    public AddProductToCartResponse createAddProductToCartResponse() {
        return new AddProductToCartResponse();
    }

    /**
     * Create an instance of {@link GetOrderByOrderName }
     * 
     */
    public GetOrderByOrderName createGetOrderByOrderName() {
        return new GetOrderByOrderName();
    }

    /**
     * Create an instance of {@link GetProductQuantityInCartByProductIdResponse }
     * 
     */
    public GetProductQuantityInCartByProductIdResponse createGetProductQuantityInCartByProductIdResponse() {
        return new GetProductQuantityInCartByProductIdResponse();
    }

    /**
     * Create an instance of {@link GetOrderByOrderNameResponse }
     * 
     */
    public GetOrderByOrderNameResponse createGetOrderByOrderNameResponse() {
        return new GetOrderByOrderNameResponse();
    }

    /**
     * Create an instance of {@link GetMostRecentBudgetByLocationsResponse }
     * 
     */
    public GetMostRecentBudgetByLocationsResponse createGetMostRecentBudgetByLocationsResponse() {
        return new GetMostRecentBudgetByLocationsResponse();
    }

    /**
     * Create an instance of {@link SaveOrder }
     * 
     */
    public SaveOrder createSaveOrder() {
        return new SaveOrder();
    }

    /**
     * Create an instance of {@link SaveOrderResponse }
     * 
     */
    public SaveOrderResponse createSaveOrderResponse() {
        return new SaveOrderResponse();
    }

    /**
     * Create an instance of {@link GetAllProductsInCart }
     * 
     */
    public GetAllProductsInCart createGetAllProductsInCart() {
        return new GetAllProductsInCart();
    }

    /**
     * Create an instance of {@link RemoveProductFromCart }
     * 
     */
    public RemoveProductFromCart createRemoveProductFromCart() {
        return new RemoveProductFromCart();
    }

    /**
     * Create an instance of {@link GetAllProductsInCartResponse }
     * 
     */
    public GetAllProductsInCartResponse createGetAllProductsInCartResponse() {
        return new GetAllProductsInCartResponse();
    }

    /**
     * Create an instance of {@link UpdateProductQuantityInCart }
     * 
     */
    public UpdateProductQuantityInCart createUpdateProductQuantityInCart() {
        return new UpdateProductQuantityInCart();
    }

    /**
     * Create an instance of {@link RemoveProductFromCartResponse }
     * 
     */
    public RemoveProductFromCartResponse createRemoveProductFromCartResponse() {
        return new RemoveProductFromCartResponse();
    }

    /**
     * Create an instance of {@link UpdateProductQuantityInCartResponse }
     * 
     */
    public UpdateProductQuantityInCartResponse createUpdateProductQuantityInCartResponse() {
        return new UpdateProductQuantityInCartResponse();
    }

    /**
     * Create an instance of {@link GetAllProductsInCartByProductType }
     * 
     */
    public GetAllProductsInCartByProductType createGetAllProductsInCartByProductType() {
        return new GetAllProductsInCartByProductType();
    }

    /**
     * Create an instance of {@link GetAllProductsInCartByProductTypeResponse }
     * 
     */
    public GetAllProductsInCartByProductTypeResponse createGetAllProductsInCartByProductTypeResponse() {
        return new GetAllProductsInCartByProductTypeResponse();
    }

    /**
     * Create an instance of {@link BudgetBean }
     * 
     */
    public BudgetBean createBudgetBean() {
        return new BudgetBean();
    }

    /**
     * Create an instance of {@link OrderBean }
     * 
     */
    public OrderBean createOrderBean() {
        return new OrderBean();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateProductQuantityInCartResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cart.service.sirius.com/cart/wsdl", name = "updateProductQuantityInCartResponse")
    public JAXBElement<UpdateProductQuantityInCartResponse> createUpdateProductQuantityInCartResponse(UpdateProductQuantityInCartResponse value) {
        return new JAXBElement<UpdateProductQuantityInCartResponse>(_UpdateProductQuantityInCartResponse_QNAME, UpdateProductQuantityInCartResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveProductFromCartResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cart.service.sirius.com/cart/wsdl", name = "removeProductFromCartResponse")
    public JAXBElement<RemoveProductFromCartResponse> createRemoveProductFromCartResponse(RemoveProductFromCartResponse value) {
        return new JAXBElement<RemoveProductFromCartResponse>(_RemoveProductFromCartResponse_QNAME, RemoveProductFromCartResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateProductQuantityInCart }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cart.service.sirius.com/cart/wsdl", name = "updateProductQuantityInCart")
    public JAXBElement<UpdateProductQuantityInCart> createUpdateProductQuantityInCart(UpdateProductQuantityInCart value) {
        return new JAXBElement<UpdateProductQuantityInCart>(_UpdateProductQuantityInCart_QNAME, UpdateProductQuantityInCart.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllProductsInCartResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cart.service.sirius.com/cart/wsdl", name = "getAllProductsInCartResponse")
    public JAXBElement<GetAllProductsInCartResponse> createGetAllProductsInCartResponse(GetAllProductsInCartResponse value) {
        return new JAXBElement<GetAllProductsInCartResponse>(_GetAllProductsInCartResponse_QNAME, GetAllProductsInCartResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveProductFromCart }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cart.service.sirius.com/cart/wsdl", name = "removeProductFromCart")
    public JAXBElement<RemoveProductFromCart> createRemoveProductFromCart(RemoveProductFromCart value) {
        return new JAXBElement<RemoveProductFromCart>(_RemoveProductFromCart_QNAME, RemoveProductFromCart.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllProductsInCart }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cart.service.sirius.com/cart/wsdl", name = "getAllProductsInCart")
    public JAXBElement<GetAllProductsInCart> createGetAllProductsInCart(GetAllProductsInCart value) {
        return new JAXBElement<GetAllProductsInCart>(_GetAllProductsInCart_QNAME, GetAllProductsInCart.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SaveOrderResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cart.service.sirius.com/cart/wsdl", name = "saveOrderResponse")
    public JAXBElement<SaveOrderResponse> createSaveOrderResponse(SaveOrderResponse value) {
        return new JAXBElement<SaveOrderResponse>(_SaveOrderResponse_QNAME, SaveOrderResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SaveOrder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cart.service.sirius.com/cart/wsdl", name = "saveOrder")
    public JAXBElement<SaveOrder> createSaveOrder(SaveOrder value) {
        return new JAXBElement<SaveOrder>(_SaveOrder_QNAME, SaveOrder.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllProductsInCartByProductTypeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cart.service.sirius.com/cart/wsdl", name = "getAllProductsInCartByProductTypeResponse")
    public JAXBElement<GetAllProductsInCartByProductTypeResponse> createGetAllProductsInCartByProductTypeResponse(GetAllProductsInCartByProductTypeResponse value) {
        return new JAXBElement<GetAllProductsInCartByProductTypeResponse>(_GetAllProductsInCartByProductTypeResponse_QNAME, GetAllProductsInCartByProductTypeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllProductsInCartByProductType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cart.service.sirius.com/cart/wsdl", name = "getAllProductsInCartByProductType")
    public JAXBElement<GetAllProductsInCartByProductType> createGetAllProductsInCartByProductType(GetAllProductsInCartByProductType value) {
        return new JAXBElement<GetAllProductsInCartByProductType>(_GetAllProductsInCartByProductType_QNAME, GetAllProductsInCartByProductType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMostRecentBudgetByLocation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cart.service.sirius.com/cart/wsdl", name = "getMostRecentBudgetByLocation")
    public JAXBElement<GetMostRecentBudgetByLocation> createGetMostRecentBudgetByLocation(GetMostRecentBudgetByLocation value) {
        return new JAXBElement<GetMostRecentBudgetByLocation>(_GetMostRecentBudgetByLocation_QNAME, GetMostRecentBudgetByLocation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllOrdersByProductTypeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cart.service.sirius.com/cart/wsdl", name = "getAllOrdersByProductTypeResponse")
    public JAXBElement<GetAllOrdersByProductTypeResponse> createGetAllOrdersByProductTypeResponse(GetAllOrdersByProductTypeResponse value) {
        return new JAXBElement<GetAllOrdersByProductTypeResponse>(_GetAllOrdersByProductTypeResponse_QNAME, GetAllOrdersByProductTypeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllOrdersByProductType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cart.service.sirius.com/cart/wsdl", name = "getAllOrdersByProductType")
    public JAXBElement<GetAllOrdersByProductType> createGetAllOrdersByProductType(GetAllOrdersByProductType value) {
        return new JAXBElement<GetAllOrdersByProductType>(_GetAllOrdersByProductType_QNAME, GetAllOrdersByProductType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllSavedOrdersResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cart.service.sirius.com/cart/wsdl", name = "getAllSavedOrdersResponse")
    public JAXBElement<GetAllSavedOrdersResponse> createGetAllSavedOrdersResponse(GetAllSavedOrdersResponse value) {
        return new JAXBElement<GetAllSavedOrdersResponse>(_GetAllSavedOrdersResponse_QNAME, GetAllSavedOrdersResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllSavedOrders }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cart.service.sirius.com/cart/wsdl", name = "getAllSavedOrders")
    public JAXBElement<GetAllSavedOrders> createGetAllSavedOrders(GetAllSavedOrders value) {
        return new JAXBElement<GetAllSavedOrders>(_GetAllSavedOrders_QNAME, GetAllSavedOrders.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMostRecentBudgetByLocationsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cart.service.sirius.com/cart/wsdl", name = "getMostRecentBudgetByLocationsResponse")
    public JAXBElement<GetMostRecentBudgetByLocationsResponse> createGetMostRecentBudgetByLocationsResponse(GetMostRecentBudgetByLocationsResponse value) {
        return new JAXBElement<GetMostRecentBudgetByLocationsResponse>(_GetMostRecentBudgetByLocationsResponse_QNAME, GetMostRecentBudgetByLocationsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProductQuantityInCartByProductIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cart.service.sirius.com/cart/wsdl", name = "getProductQuantityInCartByProductIdResponse")
    public JAXBElement<GetProductQuantityInCartByProductIdResponse> createGetProductQuantityInCartByProductIdResponse(GetProductQuantityInCartByProductIdResponse value) {
        return new JAXBElement<GetProductQuantityInCartByProductIdResponse>(_GetProductQuantityInCartByProductIdResponse_QNAME, GetProductQuantityInCartByProductIdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOrderByOrderNameResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cart.service.sirius.com/cart/wsdl", name = "getOrderByOrderNameResponse")
    public JAXBElement<GetOrderByOrderNameResponse> createGetOrderByOrderNameResponse(GetOrderByOrderNameResponse value) {
        return new JAXBElement<GetOrderByOrderNameResponse>(_GetOrderByOrderNameResponse_QNAME, GetOrderByOrderNameResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProductQuantityInCartByProductId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cart.service.sirius.com/cart/wsdl", name = "getProductQuantityInCartByProductId")
    public JAXBElement<GetProductQuantityInCartByProductId> createGetProductQuantityInCartByProductId(GetProductQuantityInCartByProductId value) {
        return new JAXBElement<GetProductQuantityInCartByProductId>(_GetProductQuantityInCartByProductId_QNAME, GetProductQuantityInCartByProductId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddProductToCartResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cart.service.sirius.com/cart/wsdl", name = "addProductToCartResponse")
    public JAXBElement<AddProductToCartResponse> createAddProductToCartResponse(AddProductToCartResponse value) {
        return new JAXBElement<AddProductToCartResponse>(_AddProductToCartResponse_QNAME, AddProductToCartResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOrderByOrderName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cart.service.sirius.com/cart/wsdl", name = "getOrderByOrderName")
    public JAXBElement<GetOrderByOrderName> createGetOrderByOrderName(GetOrderByOrderName value) {
        return new JAXBElement<GetOrderByOrderName>(_GetOrderByOrderName_QNAME, GetOrderByOrderName.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddProductToCart }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cart.service.sirius.com/cart/wsdl", name = "addProductToCart")
    public JAXBElement<AddProductToCart> createAddProductToCart(AddProductToCart value) {
        return new JAXBElement<AddProductToCart>(_AddProductToCart_QNAME, AddProductToCart.class, null, value);
    }

}
