//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.service.cart.cart.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for updateProductQuantityInCartResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="updateProductQuantityInCartResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="updateProductQuantityInCartReturn" type="{http://www.w3.org/2001/XMLSchema}boolean" form="qualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateProductQuantityInCartResponse", propOrder = {
    "updateProductQuantityInCartReturn"
})
public class UpdateProductQuantityInCartResponse {

    protected boolean updateProductQuantityInCartReturn;

    /**
     * Gets the value of the updateProductQuantityInCartReturn property.
     * 
     */
    public boolean isUpdateProductQuantityInCartReturn() {
        return updateProductQuantityInCartReturn;
    }

    /**
     * Sets the value of the updateProductQuantityInCartReturn property.
     * 
     */
    public void setUpdateProductQuantityInCartReturn(boolean value) {
        this.updateProductQuantityInCartReturn = value;
    }

}
