//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.service.generate.cart.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "CartGenerateService", targetNamespace = "http://generate.service.sirius.com/cart/wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CartGenerateService {


    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod(action = "generateCart")
    @WebResult(name = "generateCartReturn", targetNamespace = "http://generate.service.sirius.com/cart/wsdl")
    @RequestWrapper(localName = "generateCart", targetNamespace = "http://generate.service.sirius.com/cart/wsdl", className = "com.sirius.service.generate.cart.wsdl.GenerateCart")
    @ResponseWrapper(localName = "generateCartResponse", targetNamespace = "http://generate.service.sirius.com/cart/wsdl", className = "com.sirius.service.generate.cart.wsdl.GenerateCartResponse")
    @Action(input = "generateCart", output = "http://generate.service.sirius.com/cart/wsdl/CartGenerateService/generateCartResponse")
    public boolean generateCart();

}
