//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.service.generate.cart.wsdl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "CartService", targetNamespace = "http://generate.service.sirius.com/cart/wsdl", wsdlLocation = "WEB-INF/wsdl/CartService.wsdl")
public class CartService_Service
    extends Service
{

    private final static URL CARTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CARTSERVICE_EXCEPTION;
    private final static QName CARTSERVICE_QNAME = new QName("http://generate.service.sirius.com/cart/wsdl", "CartService");

    static {
            CARTSERVICE_WSDL_LOCATION = com.sirius.service.generate.cart.wsdl.CartService_Service.class.getResource("/WEB-INF/wsdl/CartService.wsdl");
        WebServiceException e = null;
        if (CARTSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/CartService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CARTSERVICE_EXCEPTION = e;
    }

    public CartService_Service() {
        super(__getWsdlLocation(), CARTSERVICE_QNAME);
    }

    public CartService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARTSERVICE_QNAME, features);
    }

    public CartService_Service(URL wsdlLocation) {
        super(wsdlLocation, CARTSERVICE_QNAME);
    }

    public CartService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARTSERVICE_QNAME, features);
    }

    public CartService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CartService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CartService
     */
    @WebEndpoint(name = "cart")
    public CartService getCart() {
        return super.getPort(new QName("http://generate.service.sirius.com/cart/wsdl", "cart"), CartService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CartService
     */
    @WebEndpoint(name = "cart")
    public CartService getCart(WebServiceFeature... features) {
        return super.getPort(new QName("http://generate.service.sirius.com/cart/wsdl", "cart"), CartService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARTSERVICE_EXCEPTION!= null) {
            throw CARTSERVICE_EXCEPTION;
        }
        return CARTSERVICE_WSDL_LOCATION;
    }

}
