//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.service.generate.cart.wsdl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "GenerateCartService", targetNamespace = "http://generate.service.sirius.com/cart/wsdl", wsdlLocation = "WEB-INF/wsdl/GenerateCartService.wsdl")
public class GenerateCartService
    extends Service
{

    private final static URL GENERATECARTSERVICE_WSDL_LOCATION;
    private final static WebServiceException GENERATECARTSERVICE_EXCEPTION;
    private final static QName GENERATECARTSERVICE_QNAME = new QName("http://generate.service.sirius.com/cart/wsdl", "GenerateCartService");

    static {
            GENERATECARTSERVICE_WSDL_LOCATION = com.sirius.service.generate.cart.wsdl.GenerateCartService.class.getResource("/WEB-INF/wsdl/GenerateCartService.wsdl");
        WebServiceException e = null;
        if (GENERATECARTSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/GenerateCartService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        GENERATECARTSERVICE_EXCEPTION = e;
    }

    public GenerateCartService() {
        super(__getWsdlLocation(), GENERATECARTSERVICE_QNAME);
    }

    public GenerateCartService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GENERATECARTSERVICE_QNAME, features);
    }

    public GenerateCartService(URL wsdlLocation) {
        super(wsdlLocation, GENERATECARTSERVICE_QNAME);
    }

    public GenerateCartService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GENERATECARTSERVICE_QNAME, features);
    }

    public GenerateCartService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GenerateCartService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CartGenerateService
     */
    @WebEndpoint(name = "generate")
    public CartGenerateService getGenerate() {
        return super.getPort(new QName("http://generate.service.sirius.com/cart/wsdl", "generate"), CartGenerateService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CartGenerateService
     */
    @WebEndpoint(name = "generate")
    public CartGenerateService getGenerate(WebServiceFeature... features) {
        return super.getPort(new QName("http://generate.service.sirius.com/cart/wsdl", "generate"), CartGenerateService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GENERATECARTSERVICE_EXCEPTION!= null) {
            throw GENERATECARTSERVICE_EXCEPTION;
        }
        return GENERATECARTSERVICE_WSDL_LOCATION;
    }

}
