//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.service.generate.cart.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sirius.service.generate.cart.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GenerateCartResponse_QNAME = new QName("http://generate.service.sirius.com/cart/wsdl", "generateCartResponse");
    private final static QName _GenerateCart_QNAME = new QName("http://generate.service.sirius.com/cart/wsdl", "generateCart");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sirius.service.generate.cart.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GenerateCart }
     * 
     */
    public GenerateCart createGenerateCart() {
        return new GenerateCart();
    }

    /**
     * Create an instance of {@link GenerateCartResponse }
     * 
     */
    public GenerateCartResponse createGenerateCartResponse() {
        return new GenerateCartResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenerateCartResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://generate.service.sirius.com/cart/wsdl", name = "generateCartResponse")
    public JAXBElement<GenerateCartResponse> createGenerateCartResponse(GenerateCartResponse value) {
        return new JAXBElement<GenerateCartResponse>(_GenerateCartResponse_QNAME, GenerateCartResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenerateCart }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://generate.service.sirius.com/cart/wsdl", name = "generateCart")
    public JAXBElement<GenerateCart> createGenerateCart(GenerateCart value) {
        return new JAXBElement<GenerateCart>(_GenerateCart_QNAME, GenerateCart.class, null, value);
    }

}
