//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.mailws.mail.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "JaxwsMail", targetNamespace = "http://jaxws.mail.service.order.sirius.com/jaxws/JaxwsMail/wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JaxwsMail {


    /**
     * 
     * @param message
     * @param toAddress
     * @param subject
     * @return
     *     returns boolean
     */
    @WebMethod(action = "sendMessage")
    @WebResult(name = "sendMessageReturn", targetNamespace = "http://jaxws.mail.service.order.sirius.com/jaxws/JaxwsMail/wsdl")
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://jaxws.mail.service.order.sirius.com/jaxws/JaxwsMail/wsdl", className = "com.sirius.mailws.mail.wsdl.SendMessage")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://jaxws.mail.service.order.sirius.com/jaxws/JaxwsMail/wsdl", className = "com.sirius.mailws.mail.wsdl.SendMessageResponse")
    @Action(input = "sendMessage", output = "http://jaxws.mail.service.order.sirius.com/jaxws/JaxwsMail/wsdl/JaxwsMail/sendMessageResponse")
    public boolean sendMessage(
        @WebParam(name = "subject", targetNamespace = "http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl")
        String subject,
        @WebParam(name = "message", targetNamespace = "http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl")
        String message,
        @WebParam(name = "toAddress", targetNamespace = "http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl")
        String toAddress);

}
