//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.mailws.mail.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sirius.mailws.mail.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Message_QNAME = new QName("http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl", "message");
    private final static QName _SendMessageResponse_QNAME = new QName("http://jaxws.mail.service.order.sirius.com/jaxws/JaxwsMail/wsdl", "sendMessageResponse");
    private final static QName _SendMessage_QNAME = new QName("http://jaxws.mail.service.order.sirius.com/jaxws/JaxwsMail/wsdl", "sendMessage");
    private final static QName _ToAddress_QNAME = new QName("http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl", "toAddress");
    private final static QName _Subject_QNAME = new QName("http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl", "subject");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sirius.mailws.mail.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SendMessageResponse }
     * 
     */
    public SendMessageResponse createSendMessageResponse() {
        return new SendMessageResponse();
    }

    /**
     * Create an instance of {@link SendMessage }
     * 
     */
    public SendMessage createSendMessage() {
        return new SendMessage();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl", name = "message")
    public JAXBElement<String> createMessage(String value) {
        return new JAXBElement<String>(_Message_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendMessageResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.mail.service.order.sirius.com/jaxws/JaxwsMail/wsdl", name = "sendMessageResponse")
    public JAXBElement<SendMessageResponse> createSendMessageResponse(SendMessageResponse value) {
        return new JAXBElement<SendMessageResponse>(_SendMessageResponse_QNAME, SendMessageResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SendMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.mail.service.order.sirius.com/jaxws/JaxwsMail/wsdl", name = "sendMessage")
    public JAXBElement<SendMessage> createSendMessage(SendMessage value) {
        return new JAXBElement<SendMessage>(_SendMessage_QNAME, SendMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl", name = "toAddress")
    public JAXBElement<String> createToAddress(String value) {
        return new JAXBElement<String>(_ToAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl", name = "subject")
    public JAXBElement<String> createSubject(String value) {
        return new JAXBElement<String>(_Subject_QNAME, String.class, null, value);
    }

}
