//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.adminws.officeadmin.wsdl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "attendance", targetNamespace = "http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Attendance {


    /**
     * 
     * @param state
     * @param beginDate
     * @param endDate
     * @param city
     * @param name
     * @param email
     * @return
     *     returns java.util.List<com.sirius.adminws.officeadmin.wsdl.AttendanceRecordBean>
     */
    @WebMethod(action = "getAttendanceRecords")
    @WebResult(name = "getAttendanceRecordsReturn", targetNamespace = "http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl")
    @RequestWrapper(localName = "getAttendanceRecords", targetNamespace = "http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl", className = "com.sirius.adminws.officeadmin.wsdl.GetAttendanceRecords")
    @ResponseWrapper(localName = "getAttendanceResponse", targetNamespace = "http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl", className = "com.sirius.adminws.officeadmin.wsdl.GetAttendanceResponse")
    @Action(input = "getAttendanceRecords", output = "http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl/attendance/getAttendanceRecordsResponse")
    public List<AttendanceRecordBean> getAttendanceRecords(
        @WebParam(name = "name", targetNamespace = "http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl")
        String name,
        @WebParam(name = "email", targetNamespace = "http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl")
        String email,
        @WebParam(name = "city", targetNamespace = "http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl")
        String city,
        @WebParam(name = "state", targetNamespace = "http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl")
        String state,
        @WebParam(name = "beginDate", targetNamespace = "http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl")
        String endDate);

}
