//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.adminws.officeadmin.wsdl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "JaxwsAttendance", targetNamespace = "http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl", wsdlLocation = "WEB-INF/wsdl/JaxwsAttednance.wsdl")
public class JaxwsAttendance
    extends Service
{

    private final static URL JAXWSATTENDANCE_WSDL_LOCATION;
    private final static WebServiceException JAXWSATTENDANCE_EXCEPTION;
    private final static QName JAXWSATTENDANCE_QNAME = new QName("http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl", "JaxwsAttendance");

    static {
            JAXWSATTENDANCE_WSDL_LOCATION = com.sirius.adminws.officeadmin.wsdl.JaxwsAttendance.class.getResource("/WEB-INF/wsdl/JaxwsAttednance.wsdl");
        WebServiceException e = null;
        if (JAXWSATTENDANCE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/JaxwsAttednance.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        JAXWSATTENDANCE_EXCEPTION = e;
    }

    public JaxwsAttendance() {
        super(__getWsdlLocation(), JAXWSATTENDANCE_QNAME);
    }

    public JaxwsAttendance(WebServiceFeature... features) {
        super(__getWsdlLocation(), JAXWSATTENDANCE_QNAME, features);
    }

    public JaxwsAttendance(URL wsdlLocation) {
        super(wsdlLocation, JAXWSATTENDANCE_QNAME);
    }

    public JaxwsAttendance(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JAXWSATTENDANCE_QNAME, features);
    }

    public JaxwsAttendance(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JaxwsAttendance(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Attendance
     */
    @WebEndpoint(name = "Attendance")
    public Attendance getAttendance() {
        return super.getPort(new QName("http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl", "Attendance"), Attendance.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Attendance
     */
    @WebEndpoint(name = "Attendance")
    public Attendance getAttendance(WebServiceFeature... features) {
        return super.getPort(new QName("http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl", "Attendance"), Attendance.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JAXWSATTENDANCE_EXCEPTION!= null) {
            throw JAXWSATTENDANCE_EXCEPTION;
        }
        return JAXWSATTENDANCE_WSDL_LOCATION;
    }

}
