//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.adminws.officeadmin.wsdl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "JaxwsOfficeAdmin", targetNamespace = "http://adminws.sirius.com/officeAdmin/wsdl", wsdlLocation = "WEB-INF/wsdl/JaxwsOfficeAdmin.wsdl")
public class JaxwsOfficeAdmin
    extends Service
{

    private final static URL JAXWSOFFICEADMIN_WSDL_LOCATION;
    private final static WebServiceException JAXWSOFFICEADMIN_EXCEPTION;
    private final static QName JAXWSOFFICEADMIN_QNAME = new QName("http://adminws.sirius.com/officeAdmin/wsdl", "JaxwsOfficeAdmin");

    static {
            JAXWSOFFICEADMIN_WSDL_LOCATION = com.sirius.adminws.officeadmin.wsdl.JaxwsOfficeAdmin.class.getResource("/WEB-INF/wsdl/JaxwsOfficeAdmin.wsdl");
        WebServiceException e = null;
        if (JAXWSOFFICEADMIN_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/JaxwsOfficeAdmin.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        JAXWSOFFICEADMIN_EXCEPTION = e;
    }

    public JaxwsOfficeAdmin() {
        super(__getWsdlLocation(), JAXWSOFFICEADMIN_QNAME);
    }

    public JaxwsOfficeAdmin(WebServiceFeature... features) {
        super(__getWsdlLocation(), JAXWSOFFICEADMIN_QNAME, features);
    }

    public JaxwsOfficeAdmin(URL wsdlLocation) {
        super(wsdlLocation, JAXWSOFFICEADMIN_QNAME);
    }

    public JaxwsOfficeAdmin(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JAXWSOFFICEADMIN_QNAME, features);
    }

    public JaxwsOfficeAdmin(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JaxwsOfficeAdmin(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OfficeAdmin
     */
    @WebEndpoint(name = "officeAdmin")
    public OfficeAdmin getOfficeAdmin() {
        return super.getPort(new QName("http://adminws.sirius.com/officeAdmin/wsdl", "officeAdmin"), OfficeAdmin.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OfficeAdmin
     */
    @WebEndpoint(name = "officeAdmin")
    public OfficeAdmin getOfficeAdmin(WebServiceFeature... features) {
        return super.getPort(new QName("http://adminws.sirius.com/officeAdmin/wsdl", "officeAdmin"), OfficeAdmin.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JAXWSOFFICEADMIN_EXCEPTION!= null) {
            throw JAXWSOFFICEADMIN_EXCEPTION;
        }
        return JAXWSOFFICEADMIN_WSDL_LOCATION;
    }

}
