//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.order.service.attendance.jaxws.jaxws.attendance.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sirius.order.service.attendance.jaxws.jaxws.attendance.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetAttendanceRecords_QNAME = new QName("http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl", "getAttendanceRecords");
    private final static QName _GetAttendanceResponse_QNAME = new QName("http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl", "getAttendanceResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sirius.order.service.attendance.jaxws.jaxws.attendance.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAttendanceResponse }
     * 
     */
    public GetAttendanceResponse createGetAttendanceResponse() {
        return new GetAttendanceResponse();
    }

    /**
     * Create an instance of {@link GetAttendanceRecords }
     * 
     */
    public GetAttendanceRecords createGetAttendanceRecords() {
        return new GetAttendanceRecords();
    }

    /**
     * Create an instance of {@link AttendanceRecordBean }
     * 
     */
    public AttendanceRecordBean createAttendanceRecordBean() {
        return new AttendanceRecordBean();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAttendanceRecords }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl", name = "getAttendanceRecords")
    public JAXBElement<GetAttendanceRecords> createGetAttendanceRecords(GetAttendanceRecords value) {
        return new JAXBElement<GetAttendanceRecords>(_GetAttendanceRecords_QNAME, GetAttendanceRecords.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAttendanceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.attendance.service.order.sirius.com/jaxws/attendance/wsdl", name = "getAttendanceResponse")
    public JAXBElement<GetAttendanceResponse> createGetAttendanceResponse(GetAttendanceResponse value) {
        return new JAXBElement<GetAttendanceResponse>(_GetAttendanceResponse_QNAME, GetAttendanceResponse.class, null, value);
    }

}
