//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.attendancews.attendance.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for attendanceRecordBean complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="attendanceRecordBean">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="attendantDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="attendantEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="attendantLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="attendantName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "attendanceRecordBean", propOrder = {
    "attendantDate",
    "attendantEmail",
    "attendantLocation",
    "attendantName"
})
public class AttendanceRecordBean {

    @XmlElement(namespace = "")
    protected String attendantDate;
    @XmlElement(namespace = "")
    protected String attendantEmail;
    @XmlElement(namespace = "")
    protected String attendantLocation;
    @XmlElement(namespace = "")
    protected String attendantName;

    /**
     * Gets the value of the attendantDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttendantDate() {
        return attendantDate;
    }

    /**
     * Sets the value of the attendantDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttendantDate(String value) {
        this.attendantDate = value;
    }

    /**
     * Gets the value of the attendantEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttendantEmail() {
        return attendantEmail;
    }

    /**
     * Sets the value of the attendantEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttendantEmail(String value) {
        this.attendantEmail = value;
    }

    /**
     * Gets the value of the attendantLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttendantLocation() {
        return attendantLocation;
    }

    /**
     * Sets the value of the attendantLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttendantLocation(String value) {
        this.attendantLocation = value;
    }

    /**
     * Gets the value of the attendantName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttendantName() {
        return attendantName;
    }

    /**
     * Sets the value of the attendantName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttendantName(String value) {
        this.attendantName = value;
    }

}
