//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.employeews.employee.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "Employee", targetNamespace = "http://employeews.sirius.com/employee/wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Employee {


    /**
     * 
     * @param email
     * @return
     *     returns com.sirius.employeews.employee.wsdl.EmployeeBean
     */
    @WebMethod(action = "getEmployeeByEmail")
    @WebResult(name = "getEmployeeByEmailReturn", targetNamespace = "http://employeews.sirius.com/employee/wsdl")
    @RequestWrapper(localName = "getEmployeeByEmail", targetNamespace = "http://employeews.sirius.com/employee/wsdl", className = "com.sirius.employeews.employee.wsdl.GetEmployeeByEmail")
    @ResponseWrapper(localName = "getEmployeeByEmailResponse", targetNamespace = "http://employeews.sirius.com/employee/wsdl", className = "com.sirius.employeews.employee.wsdl.GetEmployeeByEmailResponse")
    @Action(input = "getEmployeeByEmail", output = "http://employeews.sirius.com/employee/wsdl/Employee/getEmployeeByEmailResponse")
    public EmployeeBean getEmployeeByEmail(
        @WebParam(name = "email", targetNamespace = "http://employeews.sirius.com/employee/wsdl")
        String email);

    /**
     * 
     * @param location
     * @param role
     * @param password
     * @param name
     * @param email
     * @param picture
     * @return
     *     returns boolean
     */
    @WebMethod(action = "addEmployee")
    @WebResult(name = "addEmployeeReturn", targetNamespace = "http://employeews.sirius.com/employee/wsdl")
    @RequestWrapper(localName = "addEmployee", targetNamespace = "http://employeews.sirius.com/employee/wsdl", className = "com.sirius.employeews.employee.wsdl.AddEmployee")
    @ResponseWrapper(localName = "addEmployeeResponse", targetNamespace = "http://employeews.sirius.com/employee/wsdl", className = "com.sirius.employeews.employee.wsdl.AddEmployeeResponse")
    @Action(input = "addEmployee", output = "http://employeews.sirius.com/employee/wsdl/Employee/addEmployeeResponse")
    public boolean addEmployee(
        @WebParam(name = "name", targetNamespace = "http://employeews.sirius.com/employee/wsdl")
        String name,
        @WebParam(name = "password", targetNamespace = "http://employeews.sirius.com/employee/wsdl")
        String password,
        @WebParam(name = "role", targetNamespace = "http://employeews.sirius.com/employee/wsdl")
        int role,
        @WebParam(name = "email", targetNamespace = "http://employeews.sirius.com/employee/wsdl")
        String email,
        @WebParam(name = "picture", targetNamespace = "http://employeews.sirius.com/employee/wsdl")
        byte[] picture,
        @WebParam(name = "location", targetNamespace = "http://employeews.sirius.com/employee/wsdl")
        int location);

    /**
     * 
     * @param isValid
     * @param updaterId
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod(action = "updateEmployee")
    @WebResult(name = "updateEmployeeReturn", targetNamespace = "http://employeews.sirius.com/employee/wsdl")
    @RequestWrapper(localName = "updateEmployee", targetNamespace = "http://employeews.sirius.com/employee/wsdl", className = "com.sirius.employeews.employee.wsdl.UpdateEmployee")
    @ResponseWrapper(localName = "updateEmployeeResponse", targetNamespace = "http://employeews.sirius.com/employee/wsdl", className = "com.sirius.employeews.employee.wsdl.UpdateEmployeeResponse")
    @Action(input = "updateEmployee", output = "http://employeews.sirius.com/employee/wsdl/Employee/updateEmployeeResponse")
    public boolean updateEmployee(
        @WebParam(name = "id", targetNamespace = "http://employeews.sirius.com/employee/wsdl")
        int id,
        @WebParam(name = "isValid", targetNamespace = "http://employeews.sirius.com/employee/wsdl")
        String isValid,
        @WebParam(name = "updaterId", targetNamespace = "http://employeews.sirius.com/employee/wsdl")
        int updaterId);

}
