//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.employeews.employee.wsdl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "JaxwsEmployee", targetNamespace = "http://employeews.sirius.com/employee/wsdl", wsdlLocation = "WEB-INF/wsdl/JaxwsEmployee.wsdl")
public class JaxwsEmployee
    extends Service
{

    private final static URL JAXWSEMPLOYEE_WSDL_LOCATION;
    private final static WebServiceException JAXWSEMPLOYEE_EXCEPTION;
    private final static QName JAXWSEMPLOYEE_QNAME = new QName("http://employeews.sirius.com/employee/wsdl", "JaxwsEmployee");

    static {
            JAXWSEMPLOYEE_WSDL_LOCATION = com.sirius.employeews.employee.wsdl.JaxwsEmployee.class.getResource("/WEB-INF/wsdl/JaxwsEmployee.wsdl");
        WebServiceException e = null;
        if (JAXWSEMPLOYEE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/JaxwsEmployee.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        JAXWSEMPLOYEE_EXCEPTION = e;
    }

    public JaxwsEmployee() {
        super(__getWsdlLocation(), JAXWSEMPLOYEE_QNAME);
    }

    public JaxwsEmployee(WebServiceFeature... features) {
        super(__getWsdlLocation(), JAXWSEMPLOYEE_QNAME, features);
    }

    public JaxwsEmployee(URL wsdlLocation) {
        super(wsdlLocation, JAXWSEMPLOYEE_QNAME);
    }

    public JaxwsEmployee(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JAXWSEMPLOYEE_QNAME, features);
    }

    public JaxwsEmployee(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JaxwsEmployee(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Employee
     */
    @WebEndpoint(name = "employee")
    public Employee getEmployee() {
        return super.getPort(new QName("http://employeews.sirius.com/employee/wsdl", "employee"), Employee.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Employee
     */
    @WebEndpoint(name = "employee")
    public Employee getEmployee(WebServiceFeature... features) {
        return super.getPort(new QName("http://employeews.sirius.com/employee/wsdl", "employee"), Employee.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JAXWSEMPLOYEE_EXCEPTION!= null) {
            throw JAXWSEMPLOYEE_EXCEPTION;
        }
        return JAXWSEMPLOYEE_WSDL_LOCATION;
    }

}
