//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.employeews.employee.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sirius.employeews.employee.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UpdateEmployee_QNAME = new QName("http://employeews.sirius.com/employee/wsdl", "updateEmployee");
    private final static QName _GetEmployeeByEmailResponse_QNAME = new QName("http://employeews.sirius.com/employee/wsdl", "getEmployeeByEmailResponse");
    private final static QName _AddEmployeeResponse_QNAME = new QName("http://employeews.sirius.com/employee/wsdl", "addEmployeeResponse");
    private final static QName _GetEmployeeByEmail_QNAME = new QName("http://employeews.sirius.com/employee/wsdl", "getEmployeeByEmail");
    private final static QName _AddEmployee_QNAME = new QName("http://employeews.sirius.com/employee/wsdl", "addEmployee");
    private final static QName _UpdateEmployeeResponse_QNAME = new QName("http://employeews.sirius.com/employee/wsdl", "updateEmployeeResponse");
    private final static QName _AddEmployeePicture_QNAME = new QName("http://employeews.sirius.com/employee/wsdl", "picture");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sirius.employeews.employee.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddEmployeeResponse }
     * 
     */
    public AddEmployeeResponse createAddEmployeeResponse() {
        return new AddEmployeeResponse();
    }

    /**
     * Create an instance of {@link GetEmployeeByEmail }
     * 
     */
    public GetEmployeeByEmail createGetEmployeeByEmail() {
        return new GetEmployeeByEmail();
    }

    /**
     * Create an instance of {@link GetEmployeeByEmailResponse }
     * 
     */
    public GetEmployeeByEmailResponse createGetEmployeeByEmailResponse() {
        return new GetEmployeeByEmailResponse();
    }

    /**
     * Create an instance of {@link UpdateEmployee }
     * 
     */
    public UpdateEmployee createUpdateEmployee() {
        return new UpdateEmployee();
    }

    /**
     * Create an instance of {@link UpdateEmployeeResponse }
     * 
     */
    public UpdateEmployeeResponse createUpdateEmployeeResponse() {
        return new UpdateEmployeeResponse();
    }

    /**
     * Create an instance of {@link AddEmployee }
     * 
     */
    public AddEmployee createAddEmployee() {
        return new AddEmployee();
    }

    /**
     * Create an instance of {@link EmployeeBean }
     * 
     */
    public EmployeeBean createEmployeeBean() {
        return new EmployeeBean();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateEmployee }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://employeews.sirius.com/employee/wsdl", name = "updateEmployee")
    public JAXBElement<UpdateEmployee> createUpdateEmployee(UpdateEmployee value) {
        return new JAXBElement<UpdateEmployee>(_UpdateEmployee_QNAME, UpdateEmployee.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmployeeByEmailResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://employeews.sirius.com/employee/wsdl", name = "getEmployeeByEmailResponse")
    public JAXBElement<GetEmployeeByEmailResponse> createGetEmployeeByEmailResponse(GetEmployeeByEmailResponse value) {
        return new JAXBElement<GetEmployeeByEmailResponse>(_GetEmployeeByEmailResponse_QNAME, GetEmployeeByEmailResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddEmployeeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://employeews.sirius.com/employee/wsdl", name = "addEmployeeResponse")
    public JAXBElement<AddEmployeeResponse> createAddEmployeeResponse(AddEmployeeResponse value) {
        return new JAXBElement<AddEmployeeResponse>(_AddEmployeeResponse_QNAME, AddEmployeeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmployeeByEmail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://employeews.sirius.com/employee/wsdl", name = "getEmployeeByEmail")
    public JAXBElement<GetEmployeeByEmail> createGetEmployeeByEmail(GetEmployeeByEmail value) {
        return new JAXBElement<GetEmployeeByEmail>(_GetEmployeeByEmail_QNAME, GetEmployeeByEmail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddEmployee }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://employeews.sirius.com/employee/wsdl", name = "addEmployee")
    public JAXBElement<AddEmployee> createAddEmployee(AddEmployee value) {
        return new JAXBElement<AddEmployee>(_AddEmployee_QNAME, AddEmployee.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateEmployeeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://employeews.sirius.com/employee/wsdl", name = "updateEmployeeResponse")
    public JAXBElement<UpdateEmployeeResponse> createUpdateEmployeeResponse(UpdateEmployeeResponse value) {
        return new JAXBElement<UpdateEmployeeResponse>(_UpdateEmployeeResponse_QNAME, UpdateEmployeeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://employeews.sirius.com/employee/wsdl", name = "picture", scope = AddEmployee.class)
    public JAXBElement<byte[]> createAddEmployeePicture(byte[] value) {
        return new JAXBElement<byte[]>(_AddEmployeePicture_QNAME, byte[].class, AddEmployee.class, ((byte[]) value));
    }

}
