//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.employeews.employee.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for updateEmployeeResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="updateEmployeeResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="updateEmployeeReturn" type="{http://www.w3.org/2001/XMLSchema}boolean" form="qualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateEmployeeResponse", propOrder = {
    "updateEmployeeReturn"
})
public class UpdateEmployeeResponse {

    protected boolean updateEmployeeReturn;

    /**
     * Gets the value of the updateEmployeeReturn property.
     * 
     */
    public boolean isUpdateEmployeeReturn() {
        return updateEmployeeReturn;
    }

    /**
     * Sets the value of the updateEmployeeReturn property.
     * 
     */
    public void setUpdateEmployeeReturn(boolean value) {
        this.updateEmployeeReturn = value;
    }

}
