//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.wishlistws.wishlist.wsdl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getAllEmployeesWhoLikedProductResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getAllEmployeesWhoLikedProductResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="getAllEmployeesWhoLikedProductReturn" type="{http://wishlistws.sirius.com/wishlist/wsdl}employeeBean" maxOccurs="unbounded" minOccurs="0" form="qualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAllEmployeesWhoLikedProductResponse", propOrder = {
    "getAllEmployeesWhoLikedProductReturn"
})
public class GetAllEmployeesWhoLikedProductResponse {

    @XmlElement(namespace = "http://wishlistws.sirius.com/wishlist/wsdl")
    protected List<EmployeeBean> getAllEmployeesWhoLikedProductReturn;

    /**
     * Gets the value of the getAllEmployeesWhoLikedProductReturn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the getAllEmployeesWhoLikedProductReturn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGetAllEmployeesWhoLikedProductReturn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EmployeeBean }
     * 
     * 
     */
    public List<EmployeeBean> getGetAllEmployeesWhoLikedProductReturn() {
        if (getAllEmployeesWhoLikedProductReturn == null) {
            getAllEmployeesWhoLikedProductReturn = new ArrayList<EmployeeBean>();
        }
        return this.getAllEmployeesWhoLikedProductReturn;
    }

}
