//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.wishlistws.wishlist.wsdl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "JaxwsWishlist", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl", wsdlLocation = "WEB-INF/wsdl/JaxwsWishlist.wsdl")
public class JaxwsWishlist
    extends Service
{

    private final static URL JAXWSWISHLIST_WSDL_LOCATION;
    private final static WebServiceException JAXWSWISHLIST_EXCEPTION;
    private final static QName JAXWSWISHLIST_QNAME = new QName("http://wishlistws.sirius.com/wishlist/wsdl", "JaxwsWishlist");

    static {
            JAXWSWISHLIST_WSDL_LOCATION = com.sirius.wishlistws.wishlist.wsdl.JaxwsWishlist.class.getResource("/WEB-INF/wsdl/JaxwsWishlist.wsdl");
        WebServiceException e = null;
        if (JAXWSWISHLIST_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/JaxwsWishlist.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        JAXWSWISHLIST_EXCEPTION = e;
    }

    public JaxwsWishlist() {
        super(__getWsdlLocation(), JAXWSWISHLIST_QNAME);
    }

    public JaxwsWishlist(WebServiceFeature... features) {
        super(__getWsdlLocation(), JAXWSWISHLIST_QNAME, features);
    }

    public JaxwsWishlist(URL wsdlLocation) {
        super(wsdlLocation, JAXWSWISHLIST_QNAME);
    }

    public JaxwsWishlist(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JAXWSWISHLIST_QNAME, features);
    }

    public JaxwsWishlist(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JaxwsWishlist(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Wishlist
     */
    @WebEndpoint(name = "wishlist")
    public Wishlist getWishlist() {
        return super.getPort(new QName("http://wishlistws.sirius.com/wishlist/wsdl", "wishlist"), Wishlist.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Wishlist
     */
    @WebEndpoint(name = "wishlist")
    public Wishlist getWishlist(WebServiceFeature... features) {
        return super.getPort(new QName("http://wishlistws.sirius.com/wishlist/wsdl", "wishlist"), Wishlist.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JAXWSWISHLIST_EXCEPTION!= null) {
            throw JAXWSWISHLIST_EXCEPTION;
        }
        return JAXWSWISHLIST_WSDL_LOCATION;
    }

}
