//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.wishlistws.wishlist.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sirius.wishlistws.wishlist.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AddToLikeTable_QNAME = new QName("http://wishlistws.sirius.com/wishlist/wsdl", "addToLikeTable");
    private final static QName _AddToLikeTableResponse_QNAME = new QName("http://wishlistws.sirius.com/wishlist/wsdl", "addToLikeTableResponse");
    private final static QName _GetAllEmployeesWhoLikedProducts_QNAME = new QName("http://wishlistws.sirius.com/wishlist/wsdl", "getAllEmployeesWhoLikedProducts");
    private final static QName _GetAllEmployeesWhoLikedProductsResponse_QNAME = new QName("http://wishlistws.sirius.com/wishlist/wsdl", "getAllEmployeesWhoLikedProductsResponse");
    private final static QName _GetAllProductsEmployeeLiked_QNAME = new QName("http://wishlistws.sirius.com/wishlist/wsdl", "getAllProductsEmployeeLiked");
    private final static QName _GetAllProductsEmployeeLikedResponse_QNAME = new QName("http://wishlistws.sirius.com/wishlist/wsdl", "getAllProductsEmployeeLikedResponse");
    private final static QName _RemoveFromEmployeeWishlist_QNAME = new QName("http://wishlistws.sirius.com/wishlist/wsdl", "removeFromEmployeeWishlist");
    private final static QName _RemoveFromEmployeeWishlistResponse_QNAME = new QName("http://wishlistws.sirius.com/wishlist/wsdl", "removeFromEmployeeWishlistResponse");
    private final static QName _GetAllEmployeesWhoLikedProduct_QNAME = new QName("http://wishlistws.sirius.com/wishlist/wsdl", "getAllEmployeesWhoLikedProduct");
    private final static QName _GetAllEmployeesWhoLikedProductResponse_QNAME = new QName("http://wishlistws.sirius.com/wishlist/wsdl", "getAllEmployeesWhoLikedProductResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sirius.wishlistws.wishlist.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllProductsEmployeeLiked }
     * 
     */
    public GetAllProductsEmployeeLiked createGetAllProductsEmployeeLiked() {
        return new GetAllProductsEmployeeLiked();
    }

    /**
     * Create an instance of {@link RemoveFromEmployeeWishlist }
     * 
     */
    public RemoveFromEmployeeWishlist createRemoveFromEmployeeWishlist() {
        return new RemoveFromEmployeeWishlist();
    }

    /**
     * Create an instance of {@link GetAllProductsEmployeeLikedResponse }
     * 
     */
    public GetAllProductsEmployeeLikedResponse createGetAllProductsEmployeeLikedResponse() {
        return new GetAllProductsEmployeeLikedResponse();
    }

    /**
     * Create an instance of {@link RemoveFromEmployeeWishlistResponse }
     * 
     */
    public RemoveFromEmployeeWishlistResponse createRemoveFromEmployeeWishlistResponse() {
        return new RemoveFromEmployeeWishlistResponse();
    }

    /**
     * Create an instance of {@link GetAllEmployeesWhoLikedProduct }
     * 
     */
    public GetAllEmployeesWhoLikedProduct createGetAllEmployeesWhoLikedProduct() {
        return new GetAllEmployeesWhoLikedProduct();
    }

    /**
     * Create an instance of {@link GetAllEmployeesWhoLikedProductResponse }
     * 
     */
    public GetAllEmployeesWhoLikedProductResponse createGetAllEmployeesWhoLikedProductResponse() {
        return new GetAllEmployeesWhoLikedProductResponse();
    }

    /**
     * Create an instance of {@link AddToLikeTable }
     * 
     */
    public AddToLikeTable createAddToLikeTable() {
        return new AddToLikeTable();
    }

    /**
     * Create an instance of {@link AddToLikeTableResponse }
     * 
     */
    public AddToLikeTableResponse createAddToLikeTableResponse() {
        return new AddToLikeTableResponse();
    }

    /**
     * Create an instance of {@link GetAllEmployeesWhoLikedProducts }
     * 
     */
    public GetAllEmployeesWhoLikedProducts createGetAllEmployeesWhoLikedProducts() {
        return new GetAllEmployeesWhoLikedProducts();
    }

    /**
     * Create an instance of {@link GetAllEmployeesWhoLikedProductsResponse }
     * 
     */
    public GetAllEmployeesWhoLikedProductsResponse createGetAllEmployeesWhoLikedProductsResponse() {
        return new GetAllEmployeesWhoLikedProductsResponse();
    }

    /**
     * Create an instance of {@link EmployeeLikeBean }
     * 
     */
    public EmployeeLikeBean createEmployeeLikeBean() {
        return new EmployeeLikeBean();
    }

    /**
     * Create an instance of {@link EmployeeBean }
     * 
     */
    public EmployeeBean createEmployeeBean() {
        return new EmployeeBean();
    }

    /**
     * Create an instance of {@link ProductBean }
     * 
     */
    public ProductBean createProductBean() {
        return new ProductBean();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddToLikeTable }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wishlistws.sirius.com/wishlist/wsdl", name = "addToLikeTable")
    public JAXBElement<AddToLikeTable> createAddToLikeTable(AddToLikeTable value) {
        return new JAXBElement<AddToLikeTable>(_AddToLikeTable_QNAME, AddToLikeTable.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddToLikeTableResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wishlistws.sirius.com/wishlist/wsdl", name = "addToLikeTableResponse")
    public JAXBElement<AddToLikeTableResponse> createAddToLikeTableResponse(AddToLikeTableResponse value) {
        return new JAXBElement<AddToLikeTableResponse>(_AddToLikeTableResponse_QNAME, AddToLikeTableResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllEmployeesWhoLikedProducts }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wishlistws.sirius.com/wishlist/wsdl", name = "getAllEmployeesWhoLikedProducts")
    public JAXBElement<GetAllEmployeesWhoLikedProducts> createGetAllEmployeesWhoLikedProducts(GetAllEmployeesWhoLikedProducts value) {
        return new JAXBElement<GetAllEmployeesWhoLikedProducts>(_GetAllEmployeesWhoLikedProducts_QNAME, GetAllEmployeesWhoLikedProducts.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllEmployeesWhoLikedProductsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wishlistws.sirius.com/wishlist/wsdl", name = "getAllEmployeesWhoLikedProductsResponse")
    public JAXBElement<GetAllEmployeesWhoLikedProductsResponse> createGetAllEmployeesWhoLikedProductsResponse(GetAllEmployeesWhoLikedProductsResponse value) {
        return new JAXBElement<GetAllEmployeesWhoLikedProductsResponse>(_GetAllEmployeesWhoLikedProductsResponse_QNAME, GetAllEmployeesWhoLikedProductsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllProductsEmployeeLiked }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wishlistws.sirius.com/wishlist/wsdl", name = "getAllProductsEmployeeLiked")
    public JAXBElement<GetAllProductsEmployeeLiked> createGetAllProductsEmployeeLiked(GetAllProductsEmployeeLiked value) {
        return new JAXBElement<GetAllProductsEmployeeLiked>(_GetAllProductsEmployeeLiked_QNAME, GetAllProductsEmployeeLiked.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllProductsEmployeeLikedResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wishlistws.sirius.com/wishlist/wsdl", name = "getAllProductsEmployeeLikedResponse")
    public JAXBElement<GetAllProductsEmployeeLikedResponse> createGetAllProductsEmployeeLikedResponse(GetAllProductsEmployeeLikedResponse value) {
        return new JAXBElement<GetAllProductsEmployeeLikedResponse>(_GetAllProductsEmployeeLikedResponse_QNAME, GetAllProductsEmployeeLikedResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveFromEmployeeWishlist }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wishlistws.sirius.com/wishlist/wsdl", name = "removeFromEmployeeWishlist")
    public JAXBElement<RemoveFromEmployeeWishlist> createRemoveFromEmployeeWishlist(RemoveFromEmployeeWishlist value) {
        return new JAXBElement<RemoveFromEmployeeWishlist>(_RemoveFromEmployeeWishlist_QNAME, RemoveFromEmployeeWishlist.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveFromEmployeeWishlistResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wishlistws.sirius.com/wishlist/wsdl", name = "removeFromEmployeeWishlistResponse")
    public JAXBElement<RemoveFromEmployeeWishlistResponse> createRemoveFromEmployeeWishlistResponse(RemoveFromEmployeeWishlistResponse value) {
        return new JAXBElement<RemoveFromEmployeeWishlistResponse>(_RemoveFromEmployeeWishlistResponse_QNAME, RemoveFromEmployeeWishlistResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllEmployeesWhoLikedProduct }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wishlistws.sirius.com/wishlist/wsdl", name = "getAllEmployeesWhoLikedProduct")
    public JAXBElement<GetAllEmployeesWhoLikedProduct> createGetAllEmployeesWhoLikedProduct(GetAllEmployeesWhoLikedProduct value) {
        return new JAXBElement<GetAllEmployeesWhoLikedProduct>(_GetAllEmployeesWhoLikedProduct_QNAME, GetAllEmployeesWhoLikedProduct.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllEmployeesWhoLikedProductResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wishlistws.sirius.com/wishlist/wsdl", name = "getAllEmployeesWhoLikedProductResponse")
    public JAXBElement<GetAllEmployeesWhoLikedProductResponse> createGetAllEmployeesWhoLikedProductResponse(GetAllEmployeesWhoLikedProductResponse value) {
        return new JAXBElement<GetAllEmployeesWhoLikedProductResponse>(_GetAllEmployeesWhoLikedProductResponse_QNAME, GetAllEmployeesWhoLikedProductResponse.class, null, value);
    }

}
