//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.sirius.wishlistws.wishlist.wsdl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "Wishlist", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Wishlist {


    /**
     * 
     * @param employeeId
     * @param productId
     */
    @WebMethod(action = "addToLikeTable")
    @RequestWrapper(localName = "addToLikeTable", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl", className = "com.sirius.wishlistws.wishlist.wsdl.AddToLikeTable")
    @ResponseWrapper(localName = "addToLikeTableResponse", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl", className = "com.sirius.wishlistws.wishlist.wsdl.AddToLikeTableResponse")
    @Action(input = "addToLikeTable", output = "http://wishlistws.sirius.com/wishlist/wsdl/Wishlist/addToLikeTableResponse")
    public void addToLikeTable(
        @WebParam(name = "employee_id", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl")
        int employeeId,
        @WebParam(name = "product_id", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl")
        int productId);

    /**
     * 
     * @param locationId
     * @param productId
     * @return
     *     returns java.util.List<com.sirius.wishlistws.wishlist.wsdl.EmployeeBean>
     */
    @WebMethod(action = "getAllEmployeesWhoLikedProduct")
    @WebResult(name = "getAllEmployeesWhoLikedProductReturn", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl")
    @RequestWrapper(localName = "getAllEmployeesWhoLikedProduct", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl", className = "com.sirius.wishlistws.wishlist.wsdl.GetAllEmployeesWhoLikedProduct")
    @ResponseWrapper(localName = "getAllEmployeesWhoLikedProductResponse", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl", className = "com.sirius.wishlistws.wishlist.wsdl.GetAllEmployeesWhoLikedProductResponse")
    @Action(input = "getAllEmployeesWhoLikedProduct", output = "http://wishlistws.sirius.com/wishlist/wsdl/Wishlist/getAllEmployeesWhoLikedProductResponse")
    public List<EmployeeBean> getAllEmployeesWhoLikedProduct(
        @WebParam(name = "product_id", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl")
        int productId,
        @WebParam(name = "location_id", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl")
        int locationId);

    /**
     * 
     * @param employeeId
     * @return
     *     returns java.util.List<com.sirius.wishlistws.wishlist.wsdl.ProductBean>
     */
    @WebMethod(action = "getAllProductsEmployeeLiked")
    @WebResult(name = "getAllProductsEmployeeLikedReturn", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl")
    @RequestWrapper(localName = "getAllProductsEmployeeLiked", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl", className = "com.sirius.wishlistws.wishlist.wsdl.GetAllProductsEmployeeLiked")
    @ResponseWrapper(localName = "getAllProductsEmployeeLikedResponse", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl", className = "com.sirius.wishlistws.wishlist.wsdl.GetAllProductsEmployeeLikedResponse")
    @Action(input = "getAllProductsEmployeeLiked", output = "http://wishlistws.sirius.com/wishlist/wsdl/Wishlist/getAllProductsEmployeeLikedResponse")
    public List<ProductBean> getAllProductsEmployeeLiked(
        @WebParam(name = "employee_id", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl")
        int employeeId);

    /**
     * 
     * @param employeeId
     * @param productId
     */
    @WebMethod(action = "removeFromEmployeeWishlist")
    @RequestWrapper(localName = "removeFromEmployeeWishlist", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl", className = "com.sirius.wishlistws.wishlist.wsdl.RemoveFromEmployeeWishlist")
    @ResponseWrapper(localName = "removeFromEmployeeWishlistResponse", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl", className = "com.sirius.wishlistws.wishlist.wsdl.RemoveFromEmployeeWishlistResponse")
    @Action(input = "removeFromEmployeeWishlist", output = "http://wishlistws.sirius.com/wishlist/wsdl/Wishlist/removeFromEmployeeWishlistResponse")
    public void removeFromEmployeeWishlist(
        @WebParam(name = "employee_id", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl")
        int employeeId,
        @WebParam(name = "product_id", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl")
        int productId);

    /**
     * 
     * @param locationId
     * @param productList
     * @return
     *     returns java.util.List<com.sirius.wishlistws.wishlist.wsdl.EmployeeLikeBean>
     */
    @WebMethod(action = "getAllEmployeesWhoLikedProducts")
    @WebResult(name = "getAllEmployeesWhoLikedProductsReturn", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl")
    @RequestWrapper(localName = "getAllEmployeesWhoLikedProducts", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl", className = "com.sirius.wishlistws.wishlist.wsdl.GetAllEmployeesWhoLikedProducts")
    @ResponseWrapper(localName = "getAllEmployeesWhoLikedProductsResponse", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl", className = "com.sirius.wishlistws.wishlist.wsdl.GetAllEmployeesWhoLikedProductsResponse")
    @Action(input = "getAllEmployeesWhoLikedProducts", output = "http://wishlistws.sirius.com/wishlist/wsdl/Wishlist/getAllEmployeesWhoLikedProductsResponse")
    public List<EmployeeLikeBean> getAllEmployeesWhoLikedProducts(
        @WebParam(name = "productList", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl")
        List<ProductBean> productList,
        @WebParam(name = "location_id", targetNamespace = "http://wishlistws.sirius.com/wishlist/wsdl")
        int locationId);

}
